sudo: required

services:
  - docker

before_install:
  - docker build -t jochri3/natour-preprod -f Dockerfile.preprod .

script:
  - docker run -e CI=true jochri3/natour-preprod npm run test -- -coverage

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: develop

  - provider: heroku
    api_key:
      secure: $HEROKU_API_KEY
    app: natour-prod
    on:
      branch: main
